FROM apache/airflow:2.10.4-python3.12

USER root
# Java pour PySpark (pipeline.py) + dépendances build
RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jre-headless && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow
# Adaptateur dbt-trino dans le container Airflow
RUN pip install --no-cache-dir dbt-trino
